import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'EN' | 'FR'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations = {
  EN: {
    'pharmamind.title': 'PharmaMind AI',
    'pharmamind.subtitle': 'Developed for Eli Lilly',
    'developed.by': 'Developed by',
    'manuwatch.title': 'ManuWatch',
    'manuwatch.subtitle': 'Core Manufacturing Platform',
    'nav.realtime': 'Real-time Monitoring',
    'nav.realtime.desc': 'Live production data',
    'nav.oee': 'OEE Tracking',
    'nav.oee.desc': 'Overall Equipment Effectiveness',
    'nav.analytics': 'Production Analytics',
    'nav.analytics.desc': 'Advanced insights',
    'nav.maintenance': 'Predictive Maintenance',
    'nav.maintenance.desc': 'Maintenance alerts',
    'nav.quality': 'Quality Control',
    'nav.quality.desc': 'Quality metrics',
    'nav.visionqc': 'VisionQC',
    'nav.visionqc.desc': 'Computer vision QC',
    'nav.about': 'About',
    'nav.about.desc': 'Project & Team Info',
    'dashboard.title': 'Real-time Monitoring',
    'dashboard.subtitle': 'Live production data and metrics',
    'dashboard.status.active': 'Active',
    'dashboard.status.inactive': 'Inactive',
    'dashboard.status.maintenance': 'Maintenance',
    'dashboard.production.rate': 'Production Rate',
    'dashboard.quality.score': 'Quality Score',
    'dashboard.temperature': 'Temperature',
    'dashboard.pressure': 'Pressure',
    'dashboard.humidity': 'Humidity',
    'dashboard.vibration': 'Vibration',
    'dashboard.ph': 'pH Level',
    'dashboard.dissolution': 'Dissolution Rate',
    'dashboard.hardness': 'Hardness',
    'dashboard.friability': 'Friability',
    'dashboard.content.uniformity': 'Content Uniformity',
    'dashboard.api.content': 'API Content',
    'dashboard.drug.release': 'Drug Release Rate',
    'dashboard.tablets.min': 'tablets/min',
    'dashboard.degrees.c': '°C',
    'dashboard.bar': 'bar',
    'dashboard.percent': '%',
    'dashboard.mm.s': 'mm/s',
    'dashboard.newtons': 'N',
    'dashboard.mg': 'mg',
    'dashboard.realtime.active': 'Real-Time Active',
    'dashboard.last.updated': 'Last updated',
    'dashboard.refresh.10s': '10s refresh',
    'dashboard.production.line': 'Production Line',
    'dashboard.total.batches': 'Total Batches',
    'dashboard.status': 'Status',
    'dashboard.running': 'Running',
    'dashboard.error.loading.data': 'Error Loading Data',
    'dashboard.error.api.running': 'Make sure the PharmaMind API is running on localhost:8000',
    'dashboard.realtime.status.overview': 'Real-time Status Overview',
    'dashboard.system.status': 'System Status',
    'dashboard.operational': 'Operational',
    'dashboard.data.quality': 'Data Quality',
    'dashboard.excellent': 'Excellent',
    'dashboard.connection': 'Connection',
    'dashboard.stable': 'Stable',
    'dashboard.status.stopped': 'Stopped',
    'dashboard.status.unknown': 'Unknown',
    'production.lines.title': 'Production Lines',
    'production.lines.batches': 'Batches',
    'production.lines.total.batches': 'total batches',
    'production.lines.selected': 'Selected',
    'production.lines.total': 'Total',
    'production.lines.none': 'None',
    'production.line.a': 'Production Line A',
    'production.line.b': 'Production Line B',
    'production.line.c': 'Production Line C',
    'production.line.d': 'Production Line D',
    'product.cholesterol.a': 'Cholesterol Drug A',
    'product.cholesterol.b': 'Cholesterol Drug B',
    'product.cholesterol.c': 'Cholesterol Drug C',
    'product.cholesterol.d': 'Cholesterol Drug D',
    'oee.title': 'OEE Tracking',
    'oee.subtitle': 'Overall Equipment Effectiveness monitoring and analysis',
    'oee.availability': 'Availability',
    'oee.performance': 'Performance',
    'oee.quality': 'Quality',
    'oee.overall': 'Overall OEE',
    'oee.target': 'Target',
    'oee.current': 'Current',
    'oee.monitoring.active': 'OEE Monitoring Active',
    'oee.last.updated': 'Last updated',
    'oee.overall.score': 'Overall OEE Score',
    'oee.error.loading': 'Error Loading OEE Data',
    'oee.from.last.hour': 'from last hour',
    'oee.components': 'OEE Components',
    'oee.equipment.uptime': 'Equipment uptime',
    'oee.based.actual.planned': 'Based on actual vs planned production time',
    'oee.speed.efficiency': 'Speed efficiency',
    'oee.based.actual.theoretical': 'Based on actual vs theoretical cycle time',
    'oee.first.pass.yield': 'First-pass yield',
    'oee.based.quality.score': 'Based on quality score from production',
    'oee.insights.recommendations': 'OEE Insights & Recommendations',
    'oee.insights.availability.excellent': 'Excellent availability rate maintained.',
    'oee.insights.availability.improve': 'Consider reducing planned downtime and addressing unplanned stoppages.',
    'oee.insights.performance.optimal': 'Performance is within optimal range.',
    'oee.insights.performance.improve': 'Optimize cycle times and reduce minor stoppages for better performance.',
    'oee.insights.quality.excellent': 'Quality metrics are excellent.',
    'oee.insights.quality.improve': 'Focus on process improvements to reduce defects and improve first-pass yield.',
    'oee.overall.recommendation': 'Overall Recommendation',
    'oee.recommendation.immediate': 'Immediate attention required. Focus on the lowest performing component first.',
    'oee.recommendation.good': 'Good performance with room for improvement. Target specific components for optimization.',
    'oee.recommendation.excellent': 'Excellent OEE performance. Maintain current standards and look for continuous improvement opportunities.',
    'analytics.title': 'Production Analytics',
    'analytics.subtitle': 'Advanced insights and performance analysis',
    'analytics.status.active': 'Analytics Active',
    'analytics.time.range': 'Time Range',
    'analytics.kpi.production.rate': 'Production Rate',
    'analytics.kpi.quality.score': 'Quality Score',
    'analytics.kpi.uptime': 'Uptime',
    'analytics.kpi.cycle.time': 'Cycle Time',
    'analytics.efficiency.title': 'Efficiency Metrics',
    'analytics.efficiency.uptime': 'Uptime',
    'analytics.efficiency.throughput': 'Throughput',
    'analytics.efficiency.yield': 'Yield',
    'analytics.efficiency.cycle': 'Cycle Time',
    'analytics.efficiency.uptime.desc': 'Equipment availability',
    'analytics.efficiency.throughput.desc': 'Tablets per minute',
    'analytics.efficiency.yield.desc': 'First-pass yield',
    'analytics.efficiency.cycle.desc': 'Seconds per tablet',
    'analytics.insights.title': 'Analytics Insights',
    'analytics.insights.production.trend': 'Production Trend',
    'analytics.insights.quality.performance': 'Quality Performance',
    'analytics.insights.efficiency.analysis': 'Efficiency Analysis',
    'analytics.insights.recommendation': 'Recommendation',
    'analytics.error.loading': 'Error Loading Analytics',
    'analytics.target': 'Target',
    'analytics.status.above.target': 'ABOVE-TARGET',
    'analytics.status.on.target': 'ON-TARGET',
    'analytics.status.below.target': 'BELOW-TARGET',
    'analytics.production.trend': 'Production Trend',
    'analytics.quality.performance': 'Quality Performance',
    'analytics.efficiency.analysis': 'Efficiency Analysis',
    'analytics.recommendation': 'Recommendation',
    'analytics.production.above.target': 'Production rate is performing above target. Consider optimizing for even higher efficiency.',
    'analytics.production.needs.improvement': 'Production rate needs improvement. Focus on reducing cycle times and minimizing stoppages.',
    'analytics.quality.excellent': 'Excellent quality performance maintained. Continue current quality control practices.',
    'analytics.quality.needs.attention': 'Quality metrics need attention. Review process parameters and quality control procedures.',
    'analytics.uptime.high': 'High uptime achieved. Focus on performance optimization for maximum throughput.',
    'analytics.uptime.below.target': 'Uptime below target. Address equipment maintenance and unplanned stoppages.',
    'analytics.excellent.performance': 'Excellent performance across all metrics. Focus on continuous improvement and predictive maintenance.',
    'analytics.improvement.strategies': 'Identify the lowest performing metric and implement targeted improvement strategies. Consider root cause analysis for persistent issues.',
    'maintenance.title': 'Predictive Maintenance',
    'maintenance.subtitle': 'Equipment health monitoring and maintenance alerts',
    'maintenance.status.active': 'Maintenance Active',
    'maintenance.equipment.health': 'Equipment Health',
    'maintenance.health.excellent': 'Excellent',
    'maintenance.health.good': 'Good',
    'maintenance.health.warning': 'Warning',
    'maintenance.health.critical': 'Critical',
    'maintenance.tablet.press': 'Tablet Press',
    'maintenance.granulation': 'Granulation Unit',
    'maintenance.coating': 'Coating Machine',
    'maintenance.packaging': 'Packaging Line',
    'maintenance.compression': 'Compression Unit',
    'maintenance.qc.system': 'Quality Control System',
    'maintenance.alerts.title': 'Maintenance Alerts',
    'maintenance.alerts.scheduled': 'Scheduled Maintenance',
    'maintenance.alerts.predictive': 'Predictive Alerts',
    'maintenance.alerts.urgent': 'Urgent Alerts',
    'maintenance.alerts.no.alerts': 'No active alerts',
    'maintenance.next.service': 'Next Service',
    'maintenance.days.remaining': 'days remaining',
    'maintenance.health.score': 'Health Score',
    'maintenance.recommendation': 'Maintenance Recommendation',
    'maintenance.monitoring.active': 'Monitoring Active',
    'maintenance.last.updated': 'Last updated',
    'maintenance.active.alerts': 'active alerts',
    'maintenance.error.loading': 'Error Loading Maintenance Data',
    'maintenance.predicted': 'Predicted',
    'maintenance.confidence': 'Confidence',
    'maintenance.schedule': 'Schedule',
    'maintenance.no.active.alerts': 'No Active Alerts',
    'maintenance.no.alerts.desc': 'All equipment is operating within normal parameters',
    'maintenance.equipment.health.status': 'Equipment Health Status',
    'maintenance.uptime': 'Uptime',
    'maintenance.performance': 'Performance',
    'maintenance.schedule.title': 'Maintenance Schedule',
    'maintenance.days': 'days',
    'maintenance.next': 'Next',
    'maintenance.last': 'Last',
    'maintenance.insights.title': 'Predictive Insights',
    'maintenance.insights.equipment.health': 'Equipment Health',
    'maintenance.insights.equipment.health.desc': 'out of equipment items are in good condition.',
    'maintenance.insights.schedule': 'Maintenance Schedule',
    'maintenance.insights.schedule.desc': 'equipment items require maintenance within 30 days.',
    'maintenance.insights.alerts': 'Predictive Alerts',
    'maintenance.insights.alerts.desc': 'potential issues detected. require immediate attention.',
    'maintenance.recommendation.immediate': 'Schedule immediate maintenance for critical alerts to prevent unplanned downtime.',
    'maintenance.recommendation.monitor': 'Monitor equipment showing warning signs and schedule preventive maintenance.',
    'maintenance.recommendation.continue': 'Continue with regular maintenance schedule. All equipment is operating optimally.',
    'maintenance.severity.low': 'LOW',
    'maintenance.severity.medium': 'MEDIUM',
    'maintenance.severity.high': 'HIGH',
    'maintenance.alert.status.active': 'ACTIVE',
    'maintenance.alert.status.scheduled': 'SCHEDULED',
    'maintenance.alert.status.resolved': 'RESOLVED',
    'maintenance.equipment.tablet.press': 'Tablet Press',
    'maintenance.equipment.granulation.unit': 'Granulation Unit',
    'maintenance.equipment.coating.machine': 'Coating Machine',
    'maintenance.equipment.packaging.line': 'Packaging Line',
    'maintenance.equipment.compression.unit': 'Compression Unit',
    'maintenance.equipment.qc.system': 'Quality Control System',
    'maintenance.alert.vibration': 'Vibration levels increasing',
    'maintenance.alert.temperature': 'Temperature deviation detected',
    'maintenance.alert.pressure': 'Pressure fluctuations observed',
    'maintenance.alert.wear': 'Wear indicators approaching threshold',
    'maintenance.alert.lubrication': 'Lubrication system needs attention',
    'maintenance.alert.motor': 'Motor efficiency declining',
    'quality.title': 'Quality Control',
    'quality.subtitle': 'Quality assurance and testing results',
    'quality.status.active': 'QC Active',
    'quality.pass.rate': 'Pass Rate',
    'quality.tests.today': 'Tests Today',
    'quality.avg.test.time': 'Avg Test Time',
    'quality.metrics.title': 'Quality Metrics',
    'quality.purity.level': 'Purity Level',
    'quality.dissolution.rate': 'Dissolution Rate',
    'quality.content.uniformity': 'Content Uniformity',
    'quality.disintegration.time': 'Disintegration Time',
    'quality.friability': 'Friability',
    'quality.hardness': 'Hardness',
    'quality.target.gte95': '≥95%',
    'quality.target.gte80': '≥80%',
    'quality.target.lte5': '≤5 min',
    'quality.target.lte1': '≤1%',
    'quality.target.gte6': '≥6 N',
    'quality.tests.title': 'Recent Quality Tests',
    'quality.test.id': 'Test ID',
    'quality.test.name': 'Test Name',
    'quality.test.result': 'Result',
    'quality.test.status': 'Status',
    'quality.test.timestamp': 'Timestamp',
    'quality.test.operator': 'Operator',
    'quality.test.pass': 'PASS',
    'quality.test.marginal': 'MARGINAL',
    'quality.test.fail': 'FAIL',
    'quality.target': 'Target',
    'quality.test.visual.inspection': 'Visual Inspection',
    'quality.test.weight.variation': 'Weight Variation',
    'quality.test.content.uniformity': 'Content Uniformity',
    'quality.test.dissolution': 'Dissolution Test',
    'quality.test.disintegration': 'Disintegration Test',
    'quality.test.friability': 'Friability Test',
    'quality.test.hardness': 'Hardness Test',
    'quality.test.moisture.content': 'Moisture Content',
    'quality.test.ph.measurement': 'pH Measurement',
    'quality.test.viscosity': 'Viscosity Test',
    'quality.insights.title': 'Quality Insights',
    'quality.insights.excellent': 'Quality Performance Excellent',
    'quality.insights.excellent.desc': 'All quality metrics are within specification limits. The production line is maintaining high quality standards with a 98.5% pass rate.',
    'quality.insights.recommendation': 'Recommendation',
    'quality.insights.recommendation.desc': 'Consider implementing additional in-process quality checks to further improve the dissolution rate consistency. Current performance is good but has room for optimization.',
    'footer.copyright': '© 2025 Karunasagar Mohansundar',
    'footer.pharmamind.version': 'PharmaMind AI v2.2.4',
    'footer.manuwatch.version': 'ManuWatch v1.0.0',
    'footer.platform': 'Eli Lilly Manufacturing Platform',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'visionqc.title': 'VisionQC',
    'visionqc.subtitle': 'Computer Vision Quality Control System',
    'visionqc.status.active': 'VisionQC Active',
    'visionqc.status.inactive': 'VisionQC Inactive',
    'visionqc.last.updated': 'Last updated',
    'visionqc.start.camera': 'Start Camera',
    'visionqc.stop.camera': 'Stop Camera',
    'visionqc.start.analysis': 'Start Analysis',
    'visionqc.stop.analysis': 'Stop Analysis',
    'visionqc.camera.feed': 'Camera Feed',
    'visionqc.camera.not.active': 'Camera not active',
    'visionqc.analyzing': 'Analyzing',
    'visionqc.detection.results': 'Detection Results',
    'visionqc.no.detections': 'No objects detected',
    'visionqc.confidence': 'Confidence',
    'visionqc.dimensions': 'Dimensions',
    'visionqc.aspect.ratio': 'Aspect Ratio',
    'visionqc.defects': 'Defects',
    'visionqc.quality.metrics': 'Quality Metrics',
    'visionqc.overall.score': 'Overall Score',
    'visionqc.dimensional.accuracy': 'Dimensional Accuracy',
    'visionqc.surface.quality': 'Surface Quality',
    'visionqc.structural.integrity': 'Structural Integrity',
    'visionqc.recommendations': 'Recommendations',
    'visionqc.instructions.title': 'How to Use VisionQC',
    'visionqc.instructions.step1': '1. Click "Start Camera" to activate your device camera',
    'visionqc.instructions.step2': '2. Position a cylindrical object (pen, bottle, tube) in the camera view',
    'visionqc.instructions.step3': '3. Click "Start Analysis" to begin real-time quality inspection',
    'visionqc.instructions.step4': '4. View detection results, quality metrics, and recommendations',
    
    // About page translations
    'about.title': 'About PharmaMind AI',
    'about.subtitle': 'Intelligent Manufacturing Analytics Platform',
    'about.tabs.project': 'About the Project',
    'about.tabs.me': 'About Me',
    'about.tabs.lilly': 'Why Lilly',
    'about.project.title': 'PharmaMind AI: Intelligent Manufacturing Analytics Platform',
    'about.project.description': 'Built in just 24 hours, PharmaMind AI represents the convergence of authentic pharmaceutical manufacturing expertise and cutting-edge artificial intelligence. This comprehensive platform demonstrates how real-world pharmaceutical data can be transformed into actionable manufacturing intelligence.',
    'about.project.architecture.title': 'Core Architecture',
    'about.project.architecture.manuwatch': 'Advanced pharmaceutical manufacturing monitoring dashboard built on the proven Spruik/Libre framework, customized for pharmaceutical operations',
    'about.project.architecture.visionqc': 'Real-time AI-powered visual quality inspection system using computer vision for universal defect detection',
    'about.project.data.title': 'Authentic Data Foundation',
    'about.project.data.batches': '1,005 authentic batch records with complete process parameters',
    'about.project.data.simulation': 'Real-time simulation using actual time-series manufacturing data',
    'about.project.data.quality': 'Authentic quality control metrics: dissolution rates, drug release profiles, impurity analysis',
    'about.project.data.analytics': 'Normalized production analytics accounting for different batch sizes (240K to 2.4M tablets)',
    'about.project.tech.title': 'Technology Stack',
    'about.project.features.title': 'Key Features',
    'about.project.features.monitoring': 'Real-time pharmaceutical manufacturing monitoring with authentic process parameters',
    'about.project.features.analytics': 'Predictive analytics based on 1,005 historical batch patterns',
    'about.project.features.vision': 'Live computer vision quality inspection for any cylindrical pharmaceutical products',
    'about.project.features.bilingual': 'Bilingual interface (English/French) for international pharmaceutical operations',
    'about.project.features.scalable': 'Production-ready architecture scalable for enterprise manufacturing environments',
    'about.project.features.enterprise': 'Enterprise-grade performance optimized for manufacturing floor deployment',
    'about.me.name': 'Karunasagar Mohansundar',
    'about.me.title': 'Healthcare-Focused Data Scientist & AI Innovation Specialist',
            'about.me.description': 'Data Scientist with 5+ years specializing in healthcare technology across global markets. Currently pursuing MSc in Healthcare Management & Data Intelligence at emlyon business school, with international exposure in China (Shanghai) and Denmark (Copenhagen).',
        'about.me.journey.title': 'Career Journey',
        'about.me.journey.description': 'Data Scientist with 5+ years specializing in healthcare technology across global markets. Currently pursuing MSc in Healthcare Management & Data Intelligence at emlyon business school, with international exposure in China (Shanghai) and Denmark (Copenhagen).',
        'about.me.journey.experience': '5+ years of healthcare data science experience',
        'about.me.journey.education': 'MSc in Healthcare Management & Data Intelligence at emlyon business school',
        'about.me.journey.international': 'International exposure in Shanghai and Copenhagen healthcare ecosystems',
        'about.me.experience.title': 'Professional Experience',
        'about.me.experience.zelis': 'Zelis Healthcare (US) - Built AI models automating 40% of manual claim reviews across 10M+ claims, improving prediction accuracy by 30%',
        'about.me.experience.exl': 'EXL Health (US) - Developed AI ensemble systems for electronic health records and medical entity recognition',
        'about.me.experience.miicare': 'MiiCare (UK) - Created IoT-based remote patient monitoring systems for elderly care',
        'about.me.experience.jpmorgan': 'JP Morgan Investment Banking - Researched $9.7B biotech acquisitions including pharmaceutical M&A analysis',
        'about.me.expertise.title': 'Technical Specializations',
        'about.me.expertise.ml': 'Machine Learning',
        'about.me.expertise.mlDesc': 'Supervised ML, deep learning architectures, ensemble methods',
        'about.me.expertise.healthcare': 'Healthcare Analytics',
        'about.me.expertise.healthcareDesc': 'Real-time patient monitoring, clinical decision support, medical imaging AI',
        'about.me.expertise.bigdata': 'Big Data Engineering',
        'about.me.expertise.bigdataDesc': 'PySpark frameworks, reducing resource usage 50% while improving processing speed 30%',
        'about.me.expertise.emerging': 'Emerging Technologies',
        'about.me.expertise.emergingDesc': 'Currently exploring quantum computing applications for personalized medicine',
        'about.me.achievements.title': 'Key Achievements',
        'about.me.achievements.automation': 'Automation of manual processes',
        'about.me.achievements.accuracy': 'Prediction accuracy improvement',
        'about.me.achievements.claims': 'Healthcare claims processed',
        'about.me.recognition.title': 'Leadership & Recognition',
        'about.me.recognition.teamz': 'Winner of TeamZ Award for Best Teams at Zelis (2024)',
        'about.me.recognition.ambassador': 'Program Ambassador at emlyon business school',
        'about.me.recognition.chairperson': 'Founded and chaired Fitness & Sports Council, achieving company "Great Place to Work" certification',
        'about.me.global.title': 'Global Healthcare Perspective',
        'about.me.global.description': 'Multilingual capabilities (Tamil, English, French) with hands-on experience across US, European, UK, and Asian healthcare systems. Deep understanding of diverse regulatory frameworks and patient care approaches across different markets.',
    'about.lilly.title': 'Why Lilly & This Role',
    'about.lilly.motivation.title': 'Personal Motivation',
    'about.lilly.motivation.description': 'As someone living with diabetes, I have a deeply personal connection to pharmaceutical manufacturing quality. I understand firsthand that insulin pen reliability isn\'t just a technical specification—it\'s about enabling millions of people worldwide to manage their condition confidently and live full lives.',
    'about.lilly.matters.title': 'Why This Internship Matters to Me',
    'about.lilly.matters.description': 'The "golden minutes" principle drives my healthcare technology passion. Early in my career, I lost a close friend because we arrived at the hospital just 10 minutes too late. This experience taught me that in healthcare, precision and timing are matters of life and death. When diabetics depend on insulin pens during emergencies, manufacturing excellence becomes critical.',
    'about.lilly.bring.title': 'What I Bring to Fegersheim',
    'about.lilly.bring.learning': 'Rapid Learning & Innovation',
    'about.lilly.bring.learningDesc': 'PharmaMind AI demonstrates my ability to quickly master complex manufacturing processes and transform them into intelligent monitoring systems—exactly the innovation mindset needed for optimizing insulin pen assembly lines',
    'about.lilly.bring.ai': 'AI-Powered Quality Systems',
    'about.lilly.bring.aiDesc': 'VisionQC shows I can build real-time monitoring solutions that integrate with existing manufacturing infrastructure, bringing cutting-edge technology to traditional manufacturing challenges',
    'about.lilly.bring.global': 'Global Healthcare Perspective',
    'about.lilly.bring.globalDesc': '5+ years across US, European, and Asian healthcare systems provides unique insights for international pharmaceutical operations, helping Lilly maintain quality standards across diverse markets',
    'about.lilly.bring.leadership': 'Implementation Leadership',
    'about.lilly.bring.leadershipDesc': 'Successfully founded employee programs that achieved measurable organizational improvements, demonstrating my commitment to driving positive change through technology and teamwork',
    'about.lilly.now.title': 'Why Now',
    'about.lilly.now.description': 'Currently based in Lyon (2 hours from Strasbourg), I\'m immediately available and developing French proficiency. My MSc program has given me deep understanding of European healthcare regulations and pharmaceutical industry frameworks—perfect timing to contribute to Lilly\'s insulin pen assembly line optimization.',
    'about.lilly.vision.title': 'Long-term Vision',
    'about.lilly.vision.description': 'This role represents the perfect intersection of my technical expertise, healthcare experience, and personal commitment to pharmaceutical quality. I want to help ensure that every insulin pen leaving Fegersheim meets the absolute highest standards—because I know personally what\'s at stake when medical devices fail.',
    'about.lilly.vision.legacy': 'Lilly pioneered insulin therapy nearly a century ago. I want to help pioneer the next generation of intelligent manufacturing systems that continue that legacy of life-saving innovation.',
  },
  FR: {
    'pharmamind.title': 'PharmaMind IA',
    'pharmamind.subtitle': 'Développé pour Eli Lilly',
    'developed.by': 'Développé par',
    'manuwatch.title': 'ManuWatch',
    'manuwatch.subtitle': 'Plateforme de Fabrication Principale',
    'nav.realtime': 'Surveillance en Temps Réel',
    'nav.realtime.desc': 'Données de production en direct',
    'nav.oee': 'Suivi OEE',
    'nav.oee.desc': 'Efficacité Globale des Équipements',
    'nav.analytics': 'Analyses de Production',
    'nav.analytics.desc': 'Aperçus avancés',
    'nav.maintenance': 'Maintenance Prédictive',
    'nav.maintenance.desc': 'Alertes de maintenance',
    'nav.quality': 'Contrôle Qualité',
    'nav.quality.desc': 'Métriques de qualité',
    'nav.visionqc': 'VisionQC',
    'nav.visionqc.desc': 'Contrôle qualité par vision',
    'dashboard.title': 'Surveillance en Temps Réel',
    'dashboard.subtitle': 'Données et métriques de production en direct',
    'dashboard.status.active': 'Actif',
    'dashboard.status.inactive': 'Inactif',
    'dashboard.status.maintenance': 'Maintenance',
    'dashboard.production.rate': 'Taux de Production',
    'dashboard.quality.score': 'Score de Qualité',
    'dashboard.temperature': 'Température',
    'dashboard.pressure': 'Pression',
    'dashboard.humidity': 'Humidité',
    'dashboard.vibration': 'Vibration',
    'dashboard.ph': 'Niveau pH',
    'dashboard.dissolution': 'Taux de Dissolution',
    'dashboard.hardness': 'Dureté',
    'dashboard.friability': 'Friabilité',
    'dashboard.content.uniformity': 'Uniformité du Contenu',
    'dashboard.api.content': 'Contenu API',
    'dashboard.drug.release': 'Taux de Libération du Médicament',
    'dashboard.tablets.min': 'comprimés/min',
    'dashboard.degrees.c': '°C',
    'dashboard.bar': 'bar',
    'dashboard.percent': '%',
    'dashboard.mm.s': 'mm/s',
    'dashboard.newtons': 'N',
    'dashboard.mg': 'mg',
    'dashboard.realtime.active': 'Actif en Temps Réel',
    'dashboard.last.updated': 'Dernière mise à jour',
    'dashboard.refresh.10s': 'rafraîchissement 10s',
    'dashboard.production.line': 'Ligne de Production',
    'dashboard.total.batches': 'Total des Lots',
    'dashboard.status': 'Statut',
    'dashboard.running': 'En Cours',
    'dashboard.error.loading.data': 'Erreur de Chargement des Données',
    'dashboard.error.api.running': 'Assurez-vous que l\'API PharmaMind fonctionne sur localhost:8000',
    'dashboard.realtime.status.overview': 'Aperçu du Statut en Temps Réel',
    'dashboard.system.status': 'Statut du Système',
    'dashboard.operational': 'Opérationnel',
    'dashboard.data.quality': 'Qualité des Données',
    'dashboard.excellent': 'Excellent',
    'dashboard.connection': 'Connexion',
    'dashboard.stable': 'Stable',
    'dashboard.status.stopped': 'Arrêté',
    'dashboard.status.unknown': 'Inconnu',
    'production.lines.title': 'Lignes de Production',
    'production.lines.batches': 'Lots',
    'production.lines.total.batches': 'lots totaux',
    'production.lines.selected': 'Sélectionné',
    'production.lines.total': 'Total',
    'production.lines.none': 'Aucun',
    'production.line.a': 'Ligne de Production A',
    'production.line.b': 'Ligne de Production B',
    'production.line.c': 'Ligne de Production C',
    'production.line.d': 'Ligne de Production D',
    'product.cholesterol.a': 'Médicament Cholestérol A',
    'product.cholesterol.b': 'Médicament Cholestérol B',
    'product.cholesterol.c': 'Médicament Cholestérol C',
    'product.cholesterol.d': 'Médicament Cholestérol D',
    'oee.title': 'Suivi OEE',
    'oee.subtitle': 'Surveillance et analyse de l\'efficacité globale des équipements',
    'oee.availability': 'Disponibilité',
    'oee.performance': 'Performance',
    'oee.quality': 'Qualité',
    'oee.overall': 'OEE Global',
    'oee.target': 'Objectif',
    'oee.current': 'Actuel',
    'oee.monitoring.active': 'Surveillance OEE Active',
    'oee.last.updated': 'Dernière mise à jour',
    'oee.overall.score': 'Score OEE Global',
    'oee.error.loading': 'Erreur de Chargement des Données OEE',
    'oee.from.last.hour': 'depuis la dernière heure',
    'oee.components': 'Composants OEE',
    'oee.equipment.uptime': 'Temps de fonctionnement des équipements',
    'oee.based.actual.planned': 'Basé sur le temps de production réel vs planifié',
    'oee.speed.efficiency': 'Efficacité de vitesse',
    'oee.based.actual.theoretical': 'Basé sur le temps de cycle réel vs théorique',
    'oee.first.pass.yield': 'Rendement premier passage',
    'oee.based.quality.score': 'Basé sur le score de qualité de production',
    'oee.insights.recommendations': 'Aperçus et Recommandations OEE',
    'oee.insights.availability.excellent': 'Taux de disponibilité excellent maintenu.',
    'oee.insights.availability.improve': 'Envisagez de réduire les temps d\'arrêt planifiés et d\'aborder les arrêts non planifiés.',
    'oee.insights.performance.optimal': 'La performance est dans la plage optimale.',
    'oee.insights.performance.improve': 'Optimisez les temps de cycle et réduisez les arrêts mineurs pour une meilleure performance.',
    'oee.insights.quality.excellent': 'Les métriques de qualité sont excellentes.',
    'oee.insights.quality.improve': 'Concentrez-vous sur les améliorations de processus pour réduire les défauts et améliorer le rendement premier passage.',
    'oee.overall.recommendation': 'Recommandation Globale',
    'oee.recommendation.immediate': 'Attention immédiate requise. Concentrez-vous d\'abord sur le composant le moins performant.',
    'oee.recommendation.good': 'Bonne performance avec une marge d\'amélioration. Ciblez des composants spécifiques pour l\'optimisation.',
    'oee.recommendation.excellent': 'Performance OEE excellente. Maintenez les standards actuels et recherchez des opportunités d\'amélioration continue.',
    'analytics.title': 'Analyses de Production',
    'analytics.subtitle': 'Aperçus avancés et analyse de performance',
    'analytics.status.active': 'Analyses Actives',
    'analytics.time.range': 'Plage Temporelle',
    'analytics.kpi.production.rate': 'Taux de Production',
    'analytics.kpi.quality.score': 'Score de Qualité',
    'analytics.kpi.uptime': 'Temps de Fonctionnement',
    'analytics.kpi.cycle.time': 'Temps de Cycle',
    'analytics.efficiency.title': 'Métriques d\'Efficacité',
    'analytics.efficiency.uptime': 'Temps de Fonctionnement',
    'analytics.efficiency.throughput': 'Débit',
    'analytics.efficiency.yield': 'Rendement',
    'analytics.efficiency.cycle': 'Temps de Cycle',
    'analytics.efficiency.uptime.desc': 'Disponibilité des équipements',
    'analytics.efficiency.throughput.desc': 'Comprimés par minute',
    'analytics.efficiency.yield.desc': 'Rendement premier passage',
    'analytics.efficiency.cycle.desc': 'Secondes par comprimé',
    'analytics.insights.title': 'Aperçus Analytiques',
    'analytics.insights.production.trend': 'Tendance de Production',
    'analytics.insights.quality.performance': 'Performance Qualité',
    'analytics.insights.efficiency.analysis': 'Analyse d\'Efficacité',
    'analytics.insights.recommendation': 'Recommandation',
    'analytics.error.loading': 'Erreur de Chargement des Analyses',
    'analytics.target': 'Objectif',
    'analytics.status.above.target': 'AU-DESSUS-OBJECTIF',
    'analytics.status.on.target': 'SUR-OBJECTIF',
    'analytics.status.below.target': 'EN-DESSOUS-OBJECTIF',
    'analytics.production.trend': 'Tendance de Production',
    'analytics.quality.performance': 'Performance Qualité',
    'analytics.efficiency.analysis': 'Analyse d\'Efficacité',
    'analytics.recommendation': 'Recommandation',
    'analytics.production.above.target': 'Le taux de production dépasse l\'objectif. Envisagez d\'optimiser pour une efficacité encore plus élevée.',
    'analytics.production.needs.improvement': 'Le taux de production nécessite une amélioration. Concentrez-vous sur la réduction des temps de cycle et la minimisation des arrêts.',
    'analytics.quality.excellent': 'Performance qualité excellente maintenue. Continuez les pratiques actuelles de contrôle qualité.',
    'analytics.quality.needs.attention': 'Les métriques de qualité nécessitent une attention. Examinez les paramètres de processus et les procédures de contrôle qualité.',
    'analytics.uptime.high': 'Temps de fonctionnement élevé atteint. Concentrez-vous sur l\'optimisation des performances pour un débit maximum.',
    'analytics.uptime.below.target': 'Temps de fonctionnement inférieur à l\'objectif. Abordez la maintenance des équipements et les arrêts non planifiés.',
    'analytics.excellent.performance': 'Performance excellente sur toutes les métriques. Concentrez-vous sur l\'amélioration continue et la maintenance prédictive.',
    'analytics.improvement.strategies': 'Identifiez la métrique la moins performante et implémentez des stratégies d\'amélioration ciblées. Envisagez une analyse des causes racines pour les problèmes persistants.',
    'maintenance.title': 'Maintenance Prédictive',
    'maintenance.subtitle': 'Surveillance de l\'état des équipements et alertes de maintenance',
    'maintenance.status.active': 'Maintenance Active',
    'maintenance.equipment.health': 'État des Équipements',
    'maintenance.health.excellent': 'Excellent',
    'maintenance.health.good': 'Bon',
    'maintenance.health.warning': 'Avertissement',
    'maintenance.health.critical': 'Critique',
    'maintenance.tablet.press': 'Presse à Comprimés',
    'maintenance.granulation': 'Unité de Granulation',
    'maintenance.coating': 'Machine d\'Enrobage',
    'maintenance.packaging': 'Ligne d\'Emballage',
    'maintenance.compression': 'Unité de Compression',
    'maintenance.qc.system': 'Système de Contrôle Qualité',
    'maintenance.alerts.title': 'Alertes de Maintenance',
    'maintenance.alerts.scheduled': 'Maintenance Programmée',
    'maintenance.alerts.predictive': 'Alertes Prédictives',
    'maintenance.alerts.urgent': 'Alertes Urgentes',
    'maintenance.alerts.no.alerts': 'Aucune alerte active',
    'maintenance.next.service': 'Prochain Service',
    'maintenance.days.remaining': 'jours restants',
    'maintenance.health.score': 'Score de Santé',
    'maintenance.recommendation': 'Recommandation de Maintenance',
    'maintenance.monitoring.active': 'Surveillance Active',
    'maintenance.last.updated': 'Dernière mise à jour',
    'maintenance.active.alerts': 'alertes actives',
    'maintenance.error.loading': 'Erreur de Chargement des Données de Maintenance',
    'maintenance.predicted': 'Prédit',
    'maintenance.confidence': 'Confiance',
    'maintenance.schedule': 'Programmer',
    'maintenance.no.active.alerts': 'Aucune Alerte Active',
    'maintenance.no.alerts.desc': 'Tous les équipements fonctionnent dans des paramètres normaux',
    'maintenance.equipment.health.status': 'État de Santé des Équipements',
    'maintenance.uptime': 'Temps de Fonctionnement',
    'maintenance.performance': 'Performance',
    'maintenance.schedule.title': 'Programme de Maintenance',
    'maintenance.days': 'jours',
    'maintenance.next': 'Prochain',
    'maintenance.last': 'Dernier',
    'maintenance.insights.title': 'Aperçus Prédictifs',
    'maintenance.insights.equipment.health': 'Santé des Équipements',
    'maintenance.insights.equipment.health.desc': 'éléments d\'équipement sur sont en bon état.',
    'maintenance.insights.schedule': 'Programme de Maintenance',
    'maintenance.insights.schedule.desc': 'éléments d\'équipement nécessitent une maintenance dans les 30 jours.',
    'maintenance.insights.alerts': 'Alertes Prédictives',
    'maintenance.insights.alerts.desc': 'problèmes potentiels détectés. nécessitent une attention immédiate.',
    'maintenance.recommendation.immediate': 'Programmez une maintenance immédiate pour les alertes critiques afin de prévenir les temps d\'arrêt non planifiés.',
    'maintenance.recommendation.monitor': 'Surveillez les équipements présentant des signes d\'avertissement et programmez une maintenance préventive.',
    'maintenance.recommendation.continue': 'Continuez avec le programme de maintenance régulier. Tous les équipements fonctionnent de manière optimale.',
    'maintenance.severity.low': 'FAIBLE',
    'maintenance.severity.medium': 'MOYEN',
    'maintenance.severity.high': 'ÉLEVÉ',
    'maintenance.alert.status.active': 'ACTIF',
    'maintenance.alert.status.scheduled': 'PROGRAMMÉ',
    'maintenance.alert.status.resolved': 'RÉSOLU',
    'maintenance.equipment.tablet.press': 'Presse à Comprimés',
    'maintenance.equipment.granulation.unit': 'Unité de Granulation',
    'maintenance.equipment.coating.machine': 'Machine d\'Enrobage',
    'maintenance.equipment.packaging.line': 'Ligne d\'Emballage',
    'maintenance.equipment.compression.unit': 'Unité de Compression',
    'maintenance.equipment.qc.system': 'Système de Contrôle Qualité',
    'maintenance.alert.vibration': 'Niveaux de vibration en augmentation',
    'maintenance.alert.temperature': 'Déviation de température détectée',
    'maintenance.alert.pressure': 'Fluctuations de pression observées',
    'maintenance.alert.wear': 'Indicateurs d\'usure approchant du seuil',
    'maintenance.alert.lubrication': 'Système de lubrification nécessite une attention',
    'maintenance.alert.motor': 'Efficacité du moteur en déclin',
    'quality.title': 'Contrôle Qualité',
    'quality.subtitle': 'Assurance qualité et résultats des tests',
    'quality.status.active': 'CQ Actif',
    'quality.pass.rate': 'Taux de Réussite',
    'quality.tests.today': 'Tests Aujourd\'hui',
    'quality.avg.test.time': 'Temps Moyen de Test',
    'quality.metrics.title': 'Métriques de Qualité',
    'quality.purity.level': 'Niveau de Pureté',
    'quality.dissolution.rate': 'Taux de Dissolution',
    'quality.content.uniformity': 'Uniformité du Contenu',
    'quality.disintegration.time': 'Temps de Désintégration',
    'quality.friability': 'Friabilité',
    'quality.hardness': 'Dureté',
    'quality.target.gte95': '≥95%',
    'quality.target.gte80': '≥80%',
    'quality.target.lte5': '≤5 min',
    'quality.target.lte1': '≤1%',
    'quality.target.gte6': '≥6 N',
    'quality.tests.title': 'Tests de Qualité Récents',
    'quality.test.id': 'ID du Test',
    'quality.test.name': 'Nom du Test',
    'quality.test.result': 'Résultat',
    'quality.test.status': 'Statut',
    'quality.test.timestamp': 'Horodatage',
    'quality.test.operator': 'Opérateur',
    'quality.test.pass': 'RÉUSSI',
    'quality.test.marginal': 'MARGINAL',
    'quality.test.fail': 'ÉCHEC',
    'quality.target': 'Objectif',
    'quality.test.visual.inspection': 'Inspection Visuelle',
    'quality.test.weight.variation': 'Variation de Poids',
    'quality.test.content.uniformity': 'Uniformité du Contenu',
    'quality.test.dissolution': 'Test de Dissolution',
    'quality.test.disintegration': 'Test de Désintégration',
    'quality.test.friability': 'Test de Friabilité',
    'quality.test.hardness': 'Test de Dureté',
    'quality.test.moisture.content': 'Teneur en Humidité',
    'quality.test.ph.measurement': 'Mesure du pH',
    'quality.test.viscosity': 'Test de Viscosité',
    'quality.insights.title': 'Aperçus Qualité',
    'quality.insights.excellent': 'Performance Qualité Excellente',
    'quality.insights.excellent.desc': 'Toutes les métriques de qualité sont dans les limites de spécification. La ligne de production maintient des standards de qualité élevés avec un taux de réussite de 98,5%.',
    'quality.insights.recommendation': 'Recommandation',
    'quality.insights.recommendation.desc': 'Envisagez d\'implémenter des vérifications de qualité supplémentaires en cours de processus pour améliorer davantage la cohérence du taux de dissolution. La performance actuelle est bonne mais a une marge d\'optimisation.',
    'footer.copyright': '© 2025 Karunasagar Mohansundar',
    'footer.pharmamind.version': 'PharmaMind IA v2.2.4',
    'footer.manuwatch.version': 'ManuWatch v1.0.0',
    'footer.platform': 'Plateforme de Fabrication Eli Lilly',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'warning': 'Avertissement',
    'info': 'Information',
    'visionqc.title': 'VisionQC',
    'visionqc.subtitle': 'Système de Contrôle Qualité par Vision Artificielle',
    'visionqc.status.active': 'VisionQC Actif',
    'visionqc.status.inactive': 'VisionQC Inactif',
    'visionqc.last.updated': 'Dernière mise à jour',
    'visionqc.start.camera': 'Démarrer Caméra',
    'visionqc.stop.camera': 'Arrêter Caméra',
    'visionqc.start.analysis': 'Démarrer Analyse',
    'visionqc.stop.analysis': 'Arrêter Analyse',
    'visionqc.camera.feed': 'Flux Caméra',
    'visionqc.camera.not.active': 'Caméra non active',
    'visionqc.analyzing': 'Analyse en cours',
    'visionqc.detection.results': 'Résultats de Détection',
    'visionqc.no.detections': 'Aucun objet détecté',
    'visionqc.confidence': 'Confiance',
    'visionqc.dimensions': 'Dimensions',
    'visionqc.aspect.ratio': 'Rapport d\'Aspect',
    'visionqc.defects': 'Défauts',
    'visionqc.quality.metrics': 'Métriques de Qualité',
    'visionqc.overall.score': 'Score Global',
    'visionqc.dimensional.accuracy': 'Précision Dimensionnelle',
    'visionqc.surface.quality': 'Qualité de Surface',
    'visionqc.structural.integrity': 'Intégrité Structurelle',
    'visionqc.recommendations': 'Recommandations',
    'visionqc.instructions.title': 'Comment Utiliser VisionQC',
    'visionqc.instructions.step1': '1. Cliquez sur "Démarrer Caméra" pour activer la caméra de votre appareil',
    'visionqc.instructions.step2': '2. Positionnez un objet cylindrique (stylo, bouteille, tube) dans le champ de vision',
    'visionqc.instructions.step3': '3. Cliquez sur "Démarrer Analyse" pour commencer l\'inspection qualité en temps réel',
    'visionqc.instructions.step4': '4. Consultez les résultats de détection, métriques de qualité et recommandations',
    
    // About page translations (French)
    'nav.about': 'À Propos',
    'nav.about.desc': 'Info Projet & Équipe',
    'about.title': 'À Propos de PharmaMind IA',
    'about.subtitle': 'Plateforme d\'Analytique de Fabrication Intelligente',
    'about.tabs.project': 'À Propos du Projet',
    'about.tabs.me': 'À Propos de Moi',
    'about.tabs.lilly': 'Pourquoi Lilly',
    'about.project.title': 'PharmaMind IA : Plateforme d\'Analytique de Fabrication Intelligente',
    'about.project.description': 'Construit en seulement 24 heures, PharmaMind IA représente la convergence d\'une expertise authentique en fabrication pharmaceutique et d\'une intelligence artificielle de pointe. Cette plateforme complète démontre comment les données pharmaceutiques du monde réel peuvent être transformées en intelligence de fabrication exploitable.',
    'about.project.architecture.title': 'Architecture Principale',
    'about.project.architecture.manuwatch': 'Tableau de bord de surveillance de fabrication pharmaceutique avancé construit sur le framework éprouvé Spruik/Libre, personnalisé pour les opérations pharmaceutiques',
    'about.project.architecture.visionqc': 'Système d\'inspection qualité visuelle alimenté par IA en temps réel utilisant la vision par ordinateur pour la détection universelle de défauts',
    'about.project.data.title': 'Fondation de Données Authentiques',
    'about.project.data.batches': '1 005 enregistrements de lots authentiques avec paramètres de processus complets',
    'about.project.data.simulation': 'Simulation en temps réel utilisant des données de fabrication de séries temporelles réelles',
    'about.project.data.quality': 'Métriques de contrôle qualité authentiques : taux de dissolution, profils de libération de médicaments, analyse d\'impuretés',
    'about.project.data.analytics': 'Analytique de production normalisée tenant compte de différentes tailles de lots (240K à 2,4M comprimés)',
    'about.project.tech.title': 'Stack Technologique',
    'about.project.features.title': 'Fonctionnalités Clés',
    'about.project.features.monitoring': 'Surveillance de fabrication pharmaceutique en temps réel avec paramètres de processus authentiques',
    'about.project.features.analytics': 'Analytique prédictive basée sur 1 005 modèles de lots historiques',
    'about.project.features.vision': 'Inspection qualité par vision par ordinateur en direct pour tout produit pharmaceutique cylindrique',
    'about.project.features.bilingual': 'Interface bilingue (Anglais/Français) pour les opérations pharmaceutiques internationales',
    'about.project.features.scalable': 'Architecture prête pour la production évolutive pour les environnements de fabrication d\'entreprise',
    'about.project.features.enterprise': 'Performance de niveau entreprise optimisée pour le déploiement en atelier de fabrication',
    'about.me.name': 'Karunasagar Mohansundar',
    'about.me.title': 'Scientifique des Données Axé sur la Santé & Spécialiste de l\'Innovation IA',
            'about.me.description': 'Scientifique des données avec 5+ ans spécialisé dans la technologie de santé à travers les marchés mondiaux. Actuellement en MSc en Gestion de la Santé et Intelligence des Données à l\'emlyon business school, avec exposition internationale en Chine (Shanghai) et Danemark (Copenhague).',
        'about.me.journey.title': 'Parcours Professionnel',
        'about.me.journey.description': 'Scientifique des données avec 5+ ans spécialisé dans la technologie de santé à travers les marchés mondiaux. Actuellement en MSc en Gestion de la Santé et Intelligence des Données à l\'emlyon business school, avec exposition internationale en Chine (Shanghai) et Danemark (Copenhague).',
        'about.me.journey.experience': '5+ ans d\'expérience en science des données de santé',
        'about.me.journey.education': 'MSc en Gestion de la Santé et Intelligence des Données à l\'emlyon business school',
        'about.me.journey.international': 'Exposition internationale dans les écosystèmes de santé de Shanghai et Copenhague',
        'about.me.experience.title': 'Expérience Professionnelle',
        'about.me.experience.zelis': 'Zelis Healthcare (US) - Construit des modèles IA automatisant 40% des examens manuels de réclamations sur 10M+ réclamations, améliorant la précision prédictive de 30%',
        'about.me.experience.exl': 'EXL Health (US) - Développé des systèmes d\'ensemble IA pour les dossiers médicaux électroniques et la reconnaissance d\'entités médicales',
        'about.me.experience.miicare': 'MiiCare (UK) - Créé des systèmes de surveillance patient à distance basés sur IoT pour les soins aux personnes âgées',
        'about.me.experience.jpmorgan': 'JP Morgan Investment Banking - Recherché des acquisitions biotech de 9,7 milliards de dollars incluant l\'analyse M&A pharmaceutique',
        'about.me.expertise.title': 'Spécialisations Techniques',
        'about.me.expertise.ml': 'Machine Learning',
        'about.me.expertise.mlDesc': 'ML supervisé, architectures d\'apprentissage profond, méthodes d\'ensemble',
        'about.me.expertise.healthcare': 'Analytique de Santé',
        'about.me.expertise.healthcareDesc': 'Surveillance patient en temps réel, support décisionnel clinique, IA d\'imagerie médicale',
        'about.me.expertise.bigdata': 'Ingénierie Big Data',
        'about.me.expertise.bigdataDesc': 'Frameworks PySpark, réduisant l\'utilisation des ressources de 50% tout en améliorant la vitesse de traitement de 30%',
        'about.me.expertise.emerging': 'Technologies Émergentes',
        'about.me.expertise.emergingDesc': 'Actuellement en exploration des applications de calcul quantique pour la médecine personnalisée',
        'about.me.achievements.title': 'Réalisations Clés',
        'about.me.achievements.automation': 'Automatisation des processus manuels',
        'about.me.achievements.accuracy': 'Amélioration de la précision prédictive',
        'about.me.achievements.claims': 'Réclamations de santé traitées',
        'about.me.recognition.title': 'Leadership & Reconnaissance',
        'about.me.recognition.teamz': 'Lauréat du Prix TeamZ pour les Meilleures Équipes chez Zelis (2024)',
        'about.me.recognition.ambassador': 'Ambassadeur de Programme à l\'emlyon business school',
        'about.me.recognition.chairperson': 'Fondé et présidé le Conseil Fitness & Sports, obtenant la certification "Great Place to Work" de l\'entreprise',
        'about.me.global.title': 'Perspective Mondiale de la Santé',
        'about.me.global.description': 'Capacités multilingues (Tamoul, Anglais, Français) avec expérience pratique à travers les systèmes de santé US, Européens, UK et Asiatiques. Compréhension approfondie des cadres réglementaires divers et approches de soins patients à travers différents marchés.',
          'about.lilly.title': 'Pourquoi Lilly & Ce Rôle',
      'about.lilly.motivation.title': 'Motivation Personnelle',
      'about.lilly.motivation.description': 'En tant que personne vivant avec le diabète, j\'ai une connexion personnelle profonde avec la qualité de fabrication pharmaceutique. Je comprends de première main que la fiabilité des stylos à insuline n\'est pas seulement une spécification technique—c\'est permettre à des millions de personnes dans le monde de gérer leur condition avec confiance et vivre pleinement.',
      'about.lilly.matters.title': 'Pourquoi Ce Stage Compte Pour Moi',
      'about.lilly.matters.description': 'Le principe des "minutes d\'or" alimente ma passion pour la technologie de santé. Au début de ma carrière, j\'ai perdu un ami proche parce que nous sommes arrivés à l\'hôpital seulement 10 minutes trop tard. Cette expérience m\'a appris qu\'en santé, la précision et le timing sont des questions de vie et de mort. Quand les diabétiques dépendent des stylos à insuline pendant les urgences, l\'excellence de fabrication devient critique.',
      'about.lilly.bring.title': 'Ce Que J\'Apporte À Fegersheim',
      'about.lilly.bring.learning': 'Apprentissage Rapide & Innovation',
      'about.lilly.bring.learningDesc': 'PharmaMind IA démontre ma capacité à maîtriser rapidement des processus de fabrication complexes et les transformer en systèmes de surveillance intelligents—exactement l\'état d\'esprit d\'innovation nécessaire pour optimiser les lignes d\'assemblage de stylos à insuline',
      'about.lilly.bring.ai': 'Systèmes de Qualité Alimentés par IA',
      'about.lilly.bring.aiDesc': 'VisionQC montre que je peux construire des solutions de surveillance en temps réel qui s\'intègrent avec l\'infrastructure de fabrication existante, apportant une technologie de pointe aux défis de fabrication traditionnels',
      'about.lilly.bring.global': 'Perspective Mondiale de la Santé',
      'about.lilly.bring.globalDesc': '5+ ans à travers les systèmes de santé US, Européens et Asiatiques fournit des aperçus uniques pour les opérations pharmaceutiques internationales, aidant Lilly à maintenir les standards de qualité à travers des marchés divers',
      'about.lilly.bring.leadership': 'Leadership d\'Implémentation',
      'about.lilly.bring.leadershipDesc': 'Fondé avec succès des programmes d\'employés qui ont atteint des améliorations organisationnelles mesurables, démontrant mon engagement à conduire un changement positif à travers la technologie et le travail d\'équipe',
      'about.lilly.now.title': 'Pourquoi Maintenant',
      'about.lilly.now.description': 'Actuellement basé à Lyon (2 heures de Strasbourg), je suis immédiatement disponible et développant ma maîtrise du français. Mon programme MSc m\'a donné une compréhension approfondie des régulations européennes de santé et des cadres de l\'industrie pharmaceutique—moment parfait pour contribuer à l\'optimisation de la ligne d\'assemblage de stylos à insuline de Lilly.',
      'about.lilly.vision.title': 'Vision à Long Terme',
      'about.lilly.vision.description': 'Ce rôle représente l\'intersection parfaite de mon expertise technique, expérience de santé et engagement personnel envers la qualité pharmaceutique. Je veux aider à assurer que chaque stylo à insuline quittant Fegersheim rencontre les standards absolument les plus élevés—parce que je sais personnellement ce qui est en jeu quand les dispositifs médicaux échouent.',
      'about.lilly.vision.legacy': 'Lilly a pionnié la thérapie à l\'insuline il y a près d\'un siècle. Je veux aider à pionnier la prochaine génération de systèmes de fabrication intelligents qui continuent cet héritage d\'innovation de sauvetage de vie.',
  }
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
